USE master 

GO
 CREATE DATABASE DT
 ON PRIMARY
 FILEGROUP DT_1_FG
 ( NAME = 'DT_1',
  FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\data\DT_1.mdf',
  SIZE=150MB,
  MAXSIZE=500MB,
  FILEGROWTH=100MB)
 
  LOG ON
(NAME=DT_2,
  FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\data\DT_log2.ldf',
    SIZE=140MB, MAXSIZE=UNLIMITED, FILEGROWTH=10%),
(NAME=DT_3,
  FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\data\DT_log3.ldf',
    SIZE=80MB, MAXSIZE=UNLIMITED, FILEGROWTH=10MB);
GO

ALTER DATABASE DT

ADD FILE ( NAME = 'DT_NDF',
  FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\data\DT_NDF.ndf',
  SIZE=40MB, MAXSIZE=100, FILEGROWTH=15%);
  MODIFY FILE (NAME = 'DT_1' , FILEGROWTH = +30MB); --?

  MODIFY FILEGROUP DT_1_FG DEFAULT;
   GO 
  CREATE TABLE PSTS
  ( NOMSKLAD INT,
    NOMDOK INT,
	NOMDOG INT,
	KODDET INT,
	KOL INT DEFAULT 0,
	DATAP date CHECK (DATAP > 01.03-2004)
);
GO
CREATE TABLE DOG 
( NOMDOG INT PRIMARY KEY,
  KODDET INT,
  DTN DATE,
  DTK DATE,
  PLANN INT,
  DOGSTOIM INT,
  CHECK (DTN > 01-04-2004 AND DTK> DTN)
);
GO
CREATE TABLE DET
( KODDET INT,
  TYPEE INT,
  NAMEDET VARCHAR,
  PLANSTOIM INT CHECK (PLANSTOIM > 0)
);
GO

ALTER TABLE DET
DROP PLANSTOIM,
ADD CHET VARCHAR;



 
 



 